// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xinnvfrdgirclrwgscnk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhpbm52ZnJkZ2lyY2xyd2dzY25rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5OTE4NjEsImV4cCI6MjA1ODU2Nzg2MX0.KdBSuxsV7R41guQbIVnaWf6rgk0ZKc8JL73PtkhBUHE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);